using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TwitcherSharp.SourceGenerator;

[Generator]
public sealed class TwitcherSharpSingletonGenerator : IIncrementalGenerator
{
    private const string SingletonInterfaceMetadataName = "TwitcherSharp.Interfaces.ITwitcherSharpSingleton`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidateClasses = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds &&
                                               cds.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)),
                transform: static (ctx, _) => GetCandidate(ctx))
            .Where(static symbol => symbol is not null)!;

        var combined = context.CompilationProvider.Combine(candidateClasses.Collect());

        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            var (compilation, candidates) = source;

            foreach (var typeSymbol in candidates.Distinct(SymbolEqualityComparer.Default))
            {
                if (typeSymbol is null)
                    continue;

                if (!ShouldGenerate(compilation, typeSymbol as INamedTypeSymbol))
                    continue;

                var sourceText = Generate(typeSymbol as INamedTypeSymbol);
                spc.AddSource($"{typeSymbol.Name}.TwitcherSharpSingleton.g.cs", SourceText.From(sourceText, Encoding.UTF8));
            }
        });
    }

    private static INamedTypeSymbol? GetCandidate(GeneratorSyntaxContext context)
        => context.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)context.Node) as INamedTypeSymbol;

    private static bool ShouldGenerate(Compilation compilation, INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeKind != TypeKind.Class)
            return false;

        return typeSymbol.AllInterfaces.Any(i =>
            i.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .EndsWith(SingletonInterfaceMetadataName, StringComparison.Ordinal));
    }

    private static string Generate(INamedTypeSymbol typeSymbol)
    {
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var typeName = typeSymbol.Name;

        var namespaceBlock = ns is null ? "" : $"namespace {ns};\n\n";

        return $$"""
// <auto-generated />
using System;
using TwitcherSharp.Interfaces;

{{namespaceBlock}}public partial class {{typeName}}
{
    public static {{typeName}} Instance
    {
        get => ITwitcherSharpSingleton<{{typeName}}>.Instance;
        private set => ITwitcherSharpSingleton<{{typeName}}>.Instance = value;
    }

    public static {{typeName}} GetInstance() => ITwitcherSharpSingleton<{{typeName}}>.GetInstance();

    public static {{typeName}} CreateInstance(Action<{{typeName}}> configure = null) =>
        ITwitcherSharpSingleton<{{typeName}}>.CreateInstance(configure);
}
""";
    }
}