// using Godot;
// using TwitcherSharp.Extensions;
// using TwitcherSharp.Interfaces;
// using TwitcherSharp.Lib.Http;
//
// namespace TwitcherSharp.Generated;
// // CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.
//
// ///<summary> Interaction with the Twitch REST API.</summary>
// // ReSharper disable once InconsistentNaming
// public partial class TwitchAPI : Node, ITwitcherSharp<TwitchAPI>
// {
//     private GodotObject _data;
//     public static TwitchAPI Instance { get; private set; }
//
//     [Signal]
//     public delegate void UnauthenticatedEventHandler();
//
//     [Signal]
//     public delegate void UnauthorizedEventHandler();
//
//     public async Task<ResponseData> Request(string path, int method, string body = "", string contentType = "", int errorCount = 0)
//     {
//         return await _data.CallAsync<ResponseData>("request", this, path, method, body, contentType, errorCount);
//     }
//
//     private void ConnectSignals()
//     {
//         _data.Connect("unauthenticated", Callable.From(EmitSignalUnauthenticated));
//         _data.Connect("unauthorized", Callable.From(EmitSignalUnauthorized));
//     }
//
//     public static TwitchAPI FromObject(GodotObject data)
//     {
//         var twitchApi = new TwitchAPI
//         {
//             _data = data,
//         };
//         Instance = twitchApi;
//         twitchApi.ConnectSignals();
//         return twitchApi;
//     }
//
//     public GodotObject ToGodotObject()
//     {
//         return _data;
//     }
// }