namespace ClassGenerator.Generator;

public static class CodeStrings
{
    public const string TwitchApiUsings = """
                                          using Godot;
                                          using TwitcherSharp.Extensions;
                                          using TwitcherSharp.Interfaces;
                                          using TwitcherSharp.Lib.Http;

                                          """;

    public const string TwitchApiHeader = """

                                          namespace TwitcherSharp.Generated;
                                          // CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

                                          ///<summary> Interaction with the Twitch REST API.</summary>
                                          public partial class TwitchApi : Node, ITwitcherSharp<TwitchApi>
                                          {
                                              private GodotObject _data;
                                              public static TwitchApi Instance { get; private set; }

                                              [Signal]
                                              public delegate void UnauthenticatedEventHandler();

                                              [Signal]
                                              public delegate void UnauthorizedEventHandler();

                                              public async Task<ResponseData> Request(string path, int method, string body = "", string contentType = "", int errorCount = 0)
                                              {
                                                  return await _data.CallAsync<ResponseData>("request", this, path, method, body, contentType, errorCount);
                                              }

                                              private void ConnectSignals()
                                              {
                                                  _data.Connect("unauthenticated", Callable.From(EmitSignalUnauthenticated));
                                                  _data.Connect("unauthorized", Callable.From(EmitSignalUnauthorized));
                                              }

                                              public static TwitchApi FromObject(GodotObject data)
                                              {
                                                  var twitchApi = new TwitchApi
                                                  {
                                                      _data = data,
                                                  };
                                                  Instance = twitchApi;
                                                  twitchApi.ConnectSignals();
                                                  return twitchApi;
                                              } 
                                              
                                              public GodotObject ToGodotObject()
                                              {
                                                   return _data;
                                              }
                                          """;

    /// <summary>
    /// parameters: root, description, className
    /// </summary>
    public const string ComponentHeader = """
                                          using TwitcherSharp.Interfaces;
                                          using TwitcherSharp.Generated.Generic;
                                          using Godot;
                                             
                                          namespace TwitcherSharp.Generated.{{root}};
                                           
                                          /// <summary> 
                                          /// {{description}} 
                                          /// </summary>
                                          public partial class {{className}} : Resource, ITwitcherSharp<{{className}}>
                                          {
                                              private GodotObject _data;
                                          """;

    public const string ComponentFromBody = """
                                              /// <summary> 
                                              /// Transforms the godot data into a {{className}} object.
                                              /// </summary> 
                                              public static {{className}} FromObject(GodotObject data)
                                              {
                                                  return new {{className}}
                                                  {
                                          """;
}