namespace ClassGenerator.Generator.Api;

public static class ApiCodeStrings
{
    public const string TwitchApiUsings = """
                                          using Godot;
                                          using TwitcherSharp.Extensions;
                                          using TwitcherSharp.Interfaces;
                                          using TwitcherSharp.Lib.Http;

                                          """;

    public const string TwitchApiHeader = """

                                          namespace TwitcherSharp.Api.Generated;
                                          // CLASS GOT AUTOGENERATED DON'T CHANGE MANUALLY. CHANGES CAN BE OVERWRITTEN EASILY.

                                          ///<summary> Interaction with the Twitch REST API.</summary>
                                          public partial class TwitchApi : RefCounted, ITwitcherSharpSingleton<TwitchApi>
                                          {
                                              private GodotObject _data;
                                              
                                              public static TwitchApi Instance { get; private set; }

                                              public bool IsLinked => _data is not null && !_data.IsQueuedForDeletion();
                                              
                                              [Signal]
                                              public delegate void UnauthenticatedEventHandler();

                                              [Signal]
                                              public delegate void UnauthorizedEventHandler();

                                              public async Task<ResponseData> Request(string path, int method, string body = "", string contentType = "", int errorCount = 0)
                                              {
                                                  return await _data.CallAsync<ResponseData>("request", this, path, method, body, contentType, errorCount);
                                              }

                                              private void ConnectSignals()
                                              {
                                                  _data.Connect("unauthenticated", Callable.From(EmitSignalUnauthenticated));
                                                  _data.Connect("unauthorized", Callable.From(EmitSignalUnauthorized));
                                              }
                                              
                                              public static TwitchApi GetOrCreateInstance()
                                              {
                                                  if (Instance != null) return Instance;
                                                  
                                                  var script = GD.Load<GDScript>("res://addons/twitcher/generated/twitch_api.gd");
                                                  var twitchApi = script.New().AsGodotObject();
                                                  var instance = twitchApi.Get("instance");
                                              
                                                  if (instance.VariantType != Variant.Type.Object)
                                                  {
                                                      var root = (Engine.GetMainLoop() as SceneTree)!.Root;
                                                      root.AddChild(twitchApi as Node);
                                                      FromObject(twitchApi);
                                                      return Instance;
                                                  }
                                                  
                                                  FromObject(instance.AsGodotObject());
                                                  return Instance;
                                              }
                                              
                                              public static TwitchApi FromObject(GodotObject data)
                                              {
                                                  if (data is null) return null;
                                                  var twitchApi = new TwitchApi
                                                  {
                                                      _data = data,
                                                  };
                                                  Instance = twitchApi;
                                                  data.SetMeta("_twitcher_sharp_instance",Instance);
                                                  twitchApi.ConnectSignals();
                                                  return twitchApi;
                                              } 
                                              
                                              public GodotObject ToGodotObject()
                                              {
                                                  if(_data is not null) return _data;
                                                  
                                                  var script = GD.Load<GDScript>("res://addons/twitcher/generated/twitch_api.gd");
                                                  _data = script.New().AsGodotObject();
                                                  _data.SetMeta("_twitcher_sharp_instance",this);
                                                  
                                                  return _data;
                                              }
                                              
                                              public void FreeInstance()
                                              {
                                                  if(_data is not null && !_data.IsQueuedForDeletion()) _data.RemoveMeta("_twitcher_sharp_instance");
                                                  Instance = null;
                                              }
                                              
                                              public override void _Notification(int what)
                                              {
                                                  if (what == NotificationPredelete) FreeInstance();
                                              }
                                          """;

    /// <summary>
    /// parameters: root
    /// </summary>
    public const string ComponentUsings = """
                                          using TwitcherSharp.Interfaces;
                                          using Godot;
                                             
                                          namespace TwitcherSharp.Api.Generated.{{root}};
                                          """;

    /// <summary>
    /// Param: className
    /// </summary>
    public const string ComponentHeader = """
                                          public partial class {{className}} : RefCounted, ITwitcherSharp<{{className}}>{{interfaces}}
                                          {
                                              private GodotObject _data;
                                          """;

    public const string ComponentFromBody = """
                                                /// <summary> 
                                                /// Transforms the godot data into a {{className}} object.
                                                /// </summary> 
                                                public static {{className}} FromObject(GodotObject data)
                                                {
                                                    if(data == null) return null;
                                            """;

    public const string InterfaceBody = """
                                        using TwitcherSharp.Interfaces;
                                        
                                        namespace TwitcherSharp.Api.Generated.{{nameSpace}};
                                        public interface {{interfaceName}} : ITwitcherSharp
                                        {
                                        """;
}