<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <PackageId>Temptica.TwitcherSharp</PackageId>
        <Version>2.5.2.1</Version>
        <Authors>Temptica</Authors>
        <Description>A C# wrapper for Twitcher, the twitch integration plugin for the Godot game engine</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://https://github.com/Temptica</PackageProjectUrl>
        <RepositoryUrl>https://https://github.com/Temptica</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <!-- Source Link — lets consumers step into your source while debugging -->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Godot.SourceGenerators" Version="4.7.0"/>
        <PackageReference Include="GodotSharp" Version="4.7.0"/>
        <PackageReference Include="GodotSharpEditor" Version="4.7.0"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Api\"/>
        <None Include="..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
